export default function ARTICLE(tx) {
  return tx.executeSql(`CREATE TABLE ARTICLE (
        AvecTaxeParaf bit NULL
      , CAActuel money NULL
      , CAAnterieur money NULL
      , ChargesFixes money NULL
      , CheminDoc nvarchar(100) NULL
      , CheminImage nvarchar(100) NULL
      , Code_Article nvarchar(18) NOT NULL
      , Code_ArticleRemp nvarchar(18) NULL
      , Code_CompteAchat nvarchar(10) NULL
      , Code_CompteInventaire nvarchar(10) NULL
      , Code_CompteVente nvarchar(10) NULL
      , Code_Conditionnement nvarchar(10) NULL
      , Code_Couleur nvarchar(10) NULL
      , Code_Devise nvarchar(4) NULL
      , Code_Famille nvarchar(4) NULL
      , Code_Four nvarchar(8) NULL
      , Code_Gamme nvarchar(10) NULL
      , Code_MotCle nvarchar(10) NULL
      , Code_PaysOrigine nvarchar(4) NULL
      , Code_qualite nvarchar(10) NULL
      , Code_SousFamille nvarchar(4) NULL
      , Code_Surface nvarchar(10) NULL
      , Code_TVA nvarchar(5) NULL
      , Code_UnAchat nvarchar(4) NULL
      , Code_UnStock nvarchar(4) NULL
      , Code_UnVente nvarchar(4) NULL
      , CodeAnalytique nvarchar(10) NULL
      , CodeIntercom nvarchar(15) NULL
      , CodeTRi nvarchar(35) NULL
      , CoefCharges float NULL
      , Commentaire nvarchar(120) NULL
      , Conditionnement float NULL
      , DateCreation datetime NULL
      , DateModif datetime NULL
      , Delai smallint NULL
      , DelaiApprov smallint NULL
      , DelaiVente smallint NULL
      , Designation nvarchar(55) NULL
      , Designation2 nvarchar(55) NULL
      , DesignationModifiable bit NULL
      , Edition bit NULL
      , GenCod nvarchar(13) NULL
      , MajCoupe float NULL
      , NumSerie bit NULL
      , Obsolete bit NULL
      , PMPA money NULL
      , PMPI money NULL
      , Poids float NULL
      , PoidsBrut float NULL
      , PrixAchat money NULL
      , PrixAchatDevise money NULL
      , PrixCumule bit NULL
      , PrixRevient money NULL
      , QteReapprov float NULL
      , ReapproAuto bit NULL
      , Rem1 float NULL
      , Rem2 float NULL
      , Rem3 float NULL
      , RemiseApp bit NULL
      , StockIni float NULL
      , StockMini float NULL
      , StyleCouleur bit NULL
      , SurConditionnement float NULL
      , TarifApp bit NULL
      , TypeArticle smallint NULL
      , TypeStock smallint NULL
      , ZoneN1 float NULL
      , ZoneN2 float NULL
      , ZoneN3 float NULL
      , ZoneN4 float NULL
      , ZoneN5 float NULL
      , ZoneT1 nvarchar(80) NULL
      , ZoneT2 nvarchar(50) NULL
      , ZoneT3 nvarchar(50) NULL
      , ZoneT4 nvarchar(50) NULL
      , ZoneT5 nvarchar(50) NULL
      , Image image NULL
      )`);
}
